import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import requirementsRouter from "./requirements";
import testCasesRouter from "./test-cases";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import calendarRouter from "./calendar";
import notificationsRouter from "./notifications";
import socialEventsRouter from "./social-events";
import aiRouter from "./ai";
import pmoReportRouter from "./pmo-report";
import redmineRouter from "./redmine";
import testExecutionRouter from "./test-execution";
import contactsRouter from "./contacts";
import rolesRouter from "./roles";
import traceabilityRouter from "./traceability";
import documentRegisterRouter from "./document-register";
import uatSignoffsRouter from "./uat-signoffs";
import dataPrepFilesRouter from "./data-prep-files";
import auditLogRouter from "./audit-log";
import defectsRouter from "./defects";
import teamsRouter from "./teams";
import milestonesRouter from "./milestones";
import requirementCommentsRouter from "./requirement-comments";
import risksRouter from "./risks";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(projectsRouter);
router.use(requirementsRouter);
router.use(testCasesRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(calendarRouter);
router.use(notificationsRouter);
router.use(socialEventsRouter);
router.use(aiRouter);
router.use(pmoReportRouter);
router.use(redmineRouter);
router.use(testExecutionRouter);
router.use(contactsRouter);
router.use(rolesRouter);
router.use(traceabilityRouter);
router.use(documentRegisterRouter);
router.use(uatSignoffsRouter);
router.use(dataPrepFilesRouter);
router.use(auditLogRouter);
router.use(defectsRouter);
router.use(teamsRouter);
router.use(milestonesRouter);
router.use(requirementCommentsRouter);
router.use(risksRouter);

export default router;
