#!/usr/bin/env python3
"""
Sync the Case ID → Playwright script links.

Scans tests/*.spec.ts for qcase(...) declarations and:
  1. writes docs/test-plans/AUTOMATION_TRACEABILITY.md (Case ID → file:line + status)
  2. fills each workbook's "Additional/Comments/Issues" column (Test Step sheet)
     with the linked script reference.

Re-run after moving/adding tests:  python3 scripts/sync-traceability.py
Requires: openpyxl. Run from artifacts/qa-automation/ or the repo root.
"""
import os
import re
import sys
from datetime import date

import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)                      # artifacts/qa-automation
ROOT = os.path.dirname(os.path.dirname(PKG))     # repo root
PLANS = os.path.join(ROOT, "docs", "test-plans")

SUITES = [
    ("SMOKE", "qapulse-smoke-tests.xlsx",      "tests/smoke.spec.ts"),
    ("FUNC",  "qapulse-functional-tests.xlsx", "tests/functional.spec.ts"),
    ("NEG",   "qapulse-negative-tests.xlsx",   "tests/negative.spec.ts"),
    ("E2E",   "qapulse-e2e-tests.xlsx",        "tests/e2e.spec.ts"),
]

# qcase("ID", "Title", ...) / qcase.manual("ID", "Title", "reason") / qcase.fixme(...)
# — declarations may span lines, so this is matched against the whole file.
DECL = re.compile(r'qcase(?:\.(manual|fixme))?\(\s*"((?:SMOKE|FUNC|NEG|E2E)-\d+)",\s*"((?:[^"\\]|\\.)*)"')

COMMENT_COL = 12  # L — Additional/Comments/Issues
STATUS_LABEL = {None: "Automated", "manual": "Manual (declared in spec as skip)", "fixme": "Fixme (blocked)"}


def scan(spec_rel: str) -> dict:
    """caseId -> (status, title, line)."""
    path = os.path.join(PKG, spec_rel)
    found = {}
    if not os.path.exists(path):
        return found
    source = open(path, encoding="utf-8").read()
    for m in DECL.finditer(source):
        lineno = source.count("\n", 0, m.start()) + 1
        found[m.group(2)] = (m.group(1), m.group(3), lineno)
    return found


def main() -> int:
    md = [
        "# Automation Traceability — Test Case ↔ Playwright Script",
        "",
        f"Generated by `artifacts/qa-automation/scripts/sync-traceability.py` on {date.today().isoformat()}.",
        "Each Case ID below links the Excel register (docs/test-plans) to its Playwright",
        "test in `artifacts/qa-automation/tests/` — the same ID is carried in the test",
        "title and a `test-case` annotation at runtime.",
        "",
    ]
    total = {"auto": 0, "manual": 0, "fixme": 0, "missing": 0}

    for prefix, workbook, spec_rel in SUITES:
        decls = scan(spec_rel)
        wb_path = os.path.join(PLANS, workbook)
        wb = openpyxl.load_workbook(wb_path)
        ws = wb["Test Step"]

        md.append(f"## {workbook} → `artifacts/qa-automation/{spec_rel}`\n")
        md.append("| Case ID | Case | Automation | Script |")
        md.append("|---|---|---|---|")

        for row in ws.iter_rows(min_row=2):
            case_id = row[0].value
            if not case_id:
                continue
            case_name = row[5].value or ""
            hit = decls.get(case_id)
            if hit:
                status, _title, lineno = hit
                ref = f"artifacts/qa-automation/{spec_rel}:{lineno}"
                label = STATUS_LABEL[status]
                total["auto" if status is None else status] += 1
                comment = f"{label} — {ref}"
                md.append(f"| {case_id} | {case_name} | {label} | `{ref}` |")
            else:
                total["missing"] += 1
                comment = "Not scripted yet"
                md.append(f"| {case_id} | {case_name} | **Missing** | — |")
            ws.cell(row=row[0].row, column=COMMENT_COL, value=comment)

        try:
            wb.save(wb_path)
            print(f"updated {wb_path}")
        except PermissionError:
            print(f"!! could not save {wb_path} (open in Excel?) — MD still written", file=sys.stderr)
        md.append("")

    md.append(
        f"**Totals:** {total['auto']} automated · {total['manual']} manual-only · "
        f"{total['fixme']} fixme · {total['missing']} missing",
    )
    out = os.path.join(PLANS, "AUTOMATION_TRACEABILITY.md")
    open(out, "w", encoding="utf-8").write("\n".join(md) + "\n")
    print(f"wrote {out}")
    print(f"totals: {total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
