name: Auto Sync and PR to Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this manually from the Actions tab anytime

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Open Pull Request using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr create \
            --repo "Autoraimix/QAPulse" \
            --head "syamilsamat:main" \
            --base "main" \
            --title "SAS: fix/improve code" \
            --body "Automated code improvement sync from syamil."
