name: Auto Sync and PR to Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request to Upstream
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: "sas-automated-patch"           # A temporary branch it will create to host the PR
          base: "main"                            # Target branch on upstream
          title: "SAS: fix/improve code"          # Your default title
          body: "Automated code improvement sync from syamil."
